const mongoose = require('mongoose');
const Schema = mongoose.Schema;
/**
 * @swagger
 * Original: the original URL. Stored without http(s)://
 * Short: the shortened URL. Should be 8 characters long.
 * Created: JS Date object representing its creation date.
 * Hit: how many times the short URL has been accessed. Starts at 0.
 * Creator: the session ID that created the shortened URL. Generated by UUIDv4. https://www.npmjs.com/package/uuid
 */
let URLSchema = new Schema({
    original: {
        type: String
    },
    short: {
        type: String
    },
    created:{
        type: Date
    },
    hit: {
        type: Number
    },
    creator: {
        type: String,
    }
});

let URL = mongoose.model('URL', URLSchema);
module.exports = URL;